### ISSUE TITLE
scope undefined

### ISSUE THREAD

**Issue by RubieV** [JAAulde/cookies#1]
Hi,

I think the library is great, however scope is not initialized at:
/\* localize natives */
var document = scope.document,

Might this be dynamically set, or initialized to document by default?

**Comment by JAAulde** [comment]
Hello, thanks for using the library and taking the time to open some issues.

On this one, note that the whole library is wrapped in an [IIFE](http://benalman.com/news/2010/11/immediately-invoked-function-expression/) starting on line 17 and ending at line 419 (in the current source). Note on line 17 that the function takes two parameters-- `scope` and `undef`. Note that on line 419, where the wrapping function is invoked, I pass only one parameter, `this`. In doing so, the body of the function receives two incoming parameters. The first, `scope` is set to whatever `this` was in the scope of invocation. The second, `undef` is an undefined value because I did not pass anything in.

I hope that all makes sense!

Thanks,
Jim
